---
title: "enesmith"
author: "Elisabeth Nesmith"
date: "3/13/2021"
output: html_document
---
```{r}
library(tidyverse)
library(raster)
library(ggplot2)
library(plotly)
```

```{r}
#load in friday movement data
#park_movement_Fri <- read.csv("~/Downloads/SDS 235/DC2-data/Movement Data/park-movement-Fri.csv")

park_movement_Sun <- read.csv("~/Downloads/SDS 235/DC2-data/Movement Data/park-movement-Sun.csv")
```


```{r}
#filtering top 1 most frequent id from lauren's rmd
important_ids_Fri <- park_movement_Fri %>% 
  filter(id == 331284)
```

```{r}
# map most frequent id on friday
# Charge the image as an R object with the "JPEG" package
library(jpeg)
library(png)
my_image <- readJPEG("Park Map.jpg")

# Set up a plot area with no plot
xcoord <- park_movement_Fri$X
ycoord <- park_movement_Fri$Y
plot(x = xcoord, y = ycoord, type='n', main="", xlab="x", ylab="y")

# Get the plot information so the image will fill the plot box, and draw it
lim <- par()
rasterImage(my_image, 
            xleft=0, xright=100, 
            ybottom=0, ytop=100)
grid()
 
#Add your plot !
points(
  x= important_ids_Fri$X, 
  y= important_ids_Fri$Y, 
  type="b", lwd=5, col="black")
```

```{r}
#find most frequent ids on Sunday
frequent_id_sun <- park_movement_Sun %>%
  group_by(id) %>%
  count(id, sort = TRUE) %>% 
  filter(n > 2500)
frequent_id_sun
```

```{r}
#filter for top id
important_ids_Sun<- park_movement_Sun %>% 
  filter(id == 1529852)
```


```{r}
# map most frequent id on Sunday
# Charge the image as an R object with the "JPEG" package
library(jpeg)
library(png)
my_image <- readJPEG("Park Map.jpg")

# Set up a plot area with no plot
xcoord <- park_movement_Sun$X
ycoord <- park_movement_Sun$Y
plot(x = xcoord, y = ycoord, type='n', main="", xlab="x", ylab="y")

# Get the plot information so the image will fill the plot box, and draw it
lim <- par()
rasterImage(my_image, 
            xleft=0, xright=100, 
            ybottom=0, ytop=100)
grid()
 
#Add your plot !
points(
  x= important_ids_Sun$X, 
  y= important_ids_Sun$Y, 
  type="b", lwd=5, col="black")
```

More ideas
- filter by time (based on timeframe most communications happened)
- filter by area (based on parts of park near where the crime happened?)
  - Scott scheduled to appear on stage (number 63 on map) and memorabilia displayed in pavillion (number 32 on map)
- see where most frequent communications happened

```{r}
#filter data to just include times 12-12:30 on Sunday and the pavillion (32 on map)
pavillion_data <- park_movement_Sun %>% 
  filter(Timestamp > "2014-6-08 12:00:00" & Timestamp < "2014-6-08 12:31:00" ) %>% 
  filter(X > 20 & X < 45) %>% 
  filter(Y > 10 & Y < 40)
```

```{r}
#check which ids had most movements around here at this time
pavillion_data %>% 
  group_by(id) %>% 
  count(id, sort = TRUE) %>% 
  filter(n > 80)
```

```{r}
#filter to top id 575508
pavillion_frequent1 <- pavillion_data %>% 
  filter(id == 575508)
```

```{r}
#static plot of this id in this timeframe on map
# Charge the image as an R object with the "JPEG" package
library(jpeg)
library(png)
my_image <- readJPEG("Park Map.jpg")

# Set up a plot area with no plot
xcoord <- park_movement_Sun$X
ycoord <- park_movement_Sun$Y
plot(x = xcoord, y = ycoord, type='n', main="", xlab="x", ylab="y")

# Get the plot information so the image will fill the plot box, and draw it
lim <- par()
rasterImage(my_image, 
            xleft=0, xright=100, 
            ybottom=0, ytop=100)
grid()
 
#Add your plot !
points(
  x= pavillion_frequent1$X, 
  y= pavillion_frequent1$Y, 
  type="b", lwd=5, col="black")
```
```{r}
#static plotly of movement on map from 12 to 12:30
fig1 <- pavillion_frequent1 %>% 
  plot_ly(x = ~X,
    y = ~Y,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    colors = "dark green",
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig1 <- fig1 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig1
```



```{r}
#animated plotly of movement on map overtime
fig2 <- pavillion_frequent1 %>% 
  plot_ly(x = ~X,
    y = ~Y,
    frame = ~Timestamp,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    colors = "dark green",
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig2 <- fig2 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig2
```



```{r}
#filter to second top id 320392
pavillion_frequent2 <- pavillion_data %>% 
  filter(id == 320392)
```

```{r}
#static plot of this id in this timeframe on map
# Charge the image as an R object with the "JPEG" package
library(jpeg)
library(png)
my_image <- readJPEG("Park Map.jpg")

# Set up a plot area with no plot
xcoord <- park_movement_Sun$X
ycoord <- park_movement_Sun$Y
plot(x = xcoord, y = ycoord, type='n', main="", xlab="x", ylab="y")

# Get the plot information so the image will fill the plot box, and draw it
lim <- par()
rasterImage(my_image, 
            xleft=0, xright=100, 
            ybottom=0, ytop=100)
grid()
 
#Add your plot !
points(
  x= pavillion_frequent2$X, 
  y= pavillion_frequent2$Y, 
  type="b", lwd=5, col="black")
```

```{r}
#static plotly of movement 12 to 12:30
fig3 <- pavillion_frequent2 %>% 
  plot_ly(x = ~X,
    y = ~Y,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    colors = "blue",
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig3 <- fig3 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig3
```

```{r}
#animated plotly of movement over time
fig4 <- pavillion_frequent2 %>% 
  plot_ly(x = ~X,
    y = ~Y,
    frame = ~Timestamp,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    colors = "blue",
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig4 <- fig4 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig4
```


```{r}
#filter to third top id 1826870
pavillion_frequent3 <- pavillion_data %>% 
  filter(id == 1826870)
```

```{r}
#static plot of this id in this timeframe on map
# Charge the image as an R object with the "JPEG" package
library(jpeg)
library(png)
my_image <- readJPEG("Park Map.jpg")

# Set up a plot area with no plot
xcoord <- park_movement_Sun$X
ycoord <- park_movement_Sun$Y
plot(x = xcoord, y = ycoord, type='n', main="", xlab="x", ylab="y")

# Get the plot information so the image will fill the plot box, and draw it
lim <- par()
rasterImage(my_image, 
            xleft=0, xright=100, 
            ybottom=0, ytop=100)
grid()
 
#Add your plot !
points(
  x= pavillion_frequent3$X, 
  y= pavillion_frequent3$Y, 
  type="b", lwd=5, col="black")
```


```{r}
#animated plotly of movement over time
fig5 <- pavillion_frequent3 %>% 
  plot_ly(x = ~X,
    y = ~Y,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    colors = "black",
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig5 <- fig5 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig5
```


```{r}
#animated plotly of movement over time
fig6 <- pavillion_frequent3 %>% 
  plot_ly(x = ~X,
    y = ~Y,
    frame = ~Timestamp,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    colors = "black",
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig6 <- fig6 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig6
```

```{r}
#trying to put all three ids on one animation
pavillion_frequents <- pavillion_data %>% 
  filter(id == 575508 | id == 320392 | id == 1826870)
```

```{r}
fig7 <- pavillion_frequents %>% 
  plot_ly(x = ~X,
    y = ~Y,
    frame = ~Timestamp,
    type = 'scatter',
    mode = 'markers',
    color = ~id,
    text = ~Timestamp) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds235-dc2/main/Park%20Map.jpg",
           xref = "x",
           yref = "y",
           x = -22,
           y = 85,
           sizex = 100,
           sizey = 100,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below")) 

fig7 <- fig7 %>% layout(
    xaxis = list(range = c(0, 99)),
    yaxis = list(range = c(0, 99)))

fig7
```






