---
title: "Lauren Low's analysis"
output: html_document
---

```{r}
library(moveVis)
library(move)
library(raster)
library(ggplot2)
library(tidyverse)
library(plotly)
library(gganimate)
```

```{r loading files}
park_movement_Fri <- read.csv("/Users/llow/Desktop/visual analytics/dc2/DC2-data/Movement Data/park-movement-Fri.csv")
park_movement_Sat <- read.csv("/Users/llow/Desktop/visual analytics/dc2/DC2-data/Movement Data/park-movement-Sat.csv")
park_movement_Sun <- read.csv("/Users/llow/Desktop/visual analytics/dc2/DC2-data/Movement Data/park-movement-Sun.csv")
```


```{r revisualizing data in df}
grouped_fri <- park_movement_Fri %>%
  group_by(id) %>%
  summarize(Timestamp, type, X, Y)
grouped_fri

grouped_sat <- park_movement_Sat %>%
  group_by(id) %>%
  summarize(Timestamp, type, X, Y)
grouped_sat

grouped_sun <- park_movement_Sun %>%
  group_by(id) %>%
  summarize(Timestamp, type, X, Y)
grouped_sun
```

```{r people who moved around the most}
fri_frequent_id <- park_movement_Fri %>%
  group_by(id) %>%
  count(id, sort = TRUE) %>%
  filter(n >= 2900)
fri_frequent_id

sat_frequent_id <- park_movement_Sat %>%
  group_by(id) %>%
  count(id, sort = TRUE) %>%
  filter(n >= 2379)
sat_frequent_id

sun_frequent_id <- park_movement_Sun %>%
  group_by(id) %>%
  count(id, sort = TRUE) %>%
  filter(n >= 2400)
sun_frequent_id
```

```{r see which "most frequent" people overlap on which days}
freq_fri_sat_join <- full_join(fri_frequent_id, sat_frequent_id,  by = "id")
freq_fri_sat_join

#can't compare sun because id wont become an integer value??
# freq_fri_sun_join <- full_join(fri_frequent_id, sun_frequent_id,  by = "id")
# freq_fri_sun_join
# 
# freq_sat_sun_join <- full_join(sat_frequent_id, sun_frequent_id,  by = "id")
# freq_sat_sun_join
```


```{r visualize most frequent ids}
freq_fri_plot <- ggplot(data = fri_frequent_id, aes(x = reorder(id, n), y = n)) +
  geom_bar(stat = "identity")
freq_fri_plot

freq_sat_plot <- ggplot(data = sat_frequent_id, aes(x = reorder(id, n), y = n)) +
  geom_bar(stat = "identity")
freq_sat_plot

freq_sun_plot <- ggplot(data = sun_frequent_id, aes(x = reorder(id, n), y = n)) +
  geom_bar(stat = "identity")
freq_sun_plot
```

```{r see x and y location of 331284 on friday}
grouped_331284 <- park_movement_Fri %>%
  group_by(id) %>%
  filter (id == 331284)
grouped_331284

px_331284 <- ggplot(grouped_331284, aes(x = Timestamp, y = X)) +
  geom_point() 
px_331284

py_331284 <- ggplot(grouped_331284, aes(x = Timestamp, y = Y)) +
  geom_point() 
py_331284
```

```{r cleaning up date}
# library(lubridate)
# park_movement_Sun
# park_movement_Sun$Timestamp <- parse_date_time(park_movement_Sun$Timestamp, "YmdHMS")
# park_movement_Sun
# 
# 
# sun_1529852 <- park_movement_Sun %>%
#   group_by(id) %>%
#   summarize(Timestamp, type, X, Y) %>%
#   mutate(id = as.character(id), 
#          time_12 = format(Timestamp, "%H:%M:%S")) %>%
#   filter(id == 1529852) %>%
#   slice(1:50)
# sun_1529852
```

```{r looking at sunay freqent ids}
sun_1529852 <- park_movement_Sun %>%
  group_by(id) %>%
  summarize(Timestamp, type, X, Y) %>%
  filter(id == 1529852 | id == 1566766 | id == 1131984 | id == 1934504 | id == 871111) %>%
  slice(1:50)
sun_1529852

```

```{r example plot}
# gapminder
# 
# ggplot(sun_1529852, aes(x = X, y = Y, color = id)) +
#   geom_point(alpha = 0.7, show.legend = FALSE) +
#   scale_x_log10() +
#   # Here comes the gganimate specific bits
#   labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
#   transition_time(Timestamp) +
#   ease_aes('linear')
```

```{r animating sunday frequent ids}
gg <- ggplot(sun_1529852, aes(X, Y, color = id, ids = id)) +
  geom_point(aes(frame = Timestamp))
gg
ggplotly(gg)
```





